#+title: Order Management with Ormas
#+options: author:nil

Copyright (c) 2014 Marco Craveiro

Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, version 1.3; with no Invariant
Sections, no Front-Cover Texts and no Back-Cover Texts.

Revision *DRAFT*, January 2014

This revision of the manual describes Ormas *master* and is available
in the following formats: HTML and PDF.

#+toc: headlines 2
#+toc: listings
#+toc: tables

* Preface

*Motto 1*:

** About This Document

This document is the official manual for Ormas. Ormas - the Order
Management System - is a suite of tools around Order Management.

If you are reading a printed copy of this manual, you can always
access the latest version online:

- [[https://github.com/DomainDrivenConsilting/dogen/blob/master/doc/manual/manual.org]]

** More Information

You can find the latest source code for Dogen at the official
repository in GitHub:

- [[https://github.com/DomainDrivenConsulting/Ormas]]

You can find details on the ongoing work in the Agile folder (look for
the latest sprint):

- [[https://github.com/DomainDrivenConsulting/dogen/tree/master/doc/agile]]

* PART I
